update reference of support@aloglia.com to new ticket link
algolia/shipjs pull request #1004
Opened 2024-07-11 13:25 UTC by palacejackson

Hey team!
The Support team is currently in a process of removing support@algolia.com email from all GitHub repos and updating it to link to the new ticket form https://alg.li/support. We kindly ask that you review the changes made removing references to support@algolia.com
Thanks!

2024-07-12 08:05 UTC, Haroenv requested changes
thanks!

2024-07-12 08:05 UTC, Haroenv commented on package.json
> +  "author": "Algolia <https://alg.li/support>",
between the brackets should be an email, instead you should do:

```suggestion
  "author": {
    "name": "Algolia",
    "url": "https://www.algolia.com"
  },
```

2024-08-14 15:26 UTC, palacejackson commented
Thanks for the tip!

2024-08-19 07:09 UTC, Haroenv approved these changes

2024-08-19 07:10 UTC, merged